import type {Metadata} from "next";
import localFont from "next/font/local";
import "./globals.css";
import ApplicationFrame from "@repo/ui/ApplicationFrame";
import {JetBrains_Mono} from "next/font/google";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

const inter = JetBrains_Mono({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={`${geistSans.variable} ${geistMono.variable} ${inter.className}`}>
    <ApplicationFrame>
      {children}
    </ApplicationFrame>
    </body>
    </html>
  );
}
