import type {Metadata} from "next";
import "./globals.css";
import ApplicationFrame from "@repo/ui/ApplicationFrame";
import {Roboto_Mono} from "next/font/google";

const robotoMono = Roboto_Mono({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={`${robotoMono.className}`}>
    <ApplicationFrame>
      {children}
    </ApplicationFrame>
    </body>
    </html>
  );
}
