import type { EmitContext } from "../emit.js";
import type { ParsedItem } from "../model.js";
import { findSoleMarker } from "../util.js";

export const README_BEGIN = "<!-- BEGIN CONTENT OVERVIEW -->";
export const README_END = "<!-- END CONTENT OVERVIEW -->";

const oneLine = (s: string): string => s.replace(/\s+/g, " ").trim();

/** The generated overview block (no markers): skills grouped by domain + a tally of other content. */
export function readmeOverviewBlock(ctx: EmitContext): string {
  const L: string[] = [];
  L.push("_Generated by `pnpm generate` - do not edit by hand. Full routing index: [`CATALOG.md`](CATALOG.md)._");

  if (ctx.skills.length > 0) {
    L.push("", "### Skills by domain");
    const buckets = new Map<string, ParsedItem[]>();
    for (const s of ctx.skills) {
      const g = s.group ?? "(ungrouped)";
      (buckets.get(g) ?? buckets.set(g, []).get(g)!).push(s);
    }
    for (const g of [...buckets.keys()].sort()) {
      const list = [...buckets.get(g)!].sort((a, b) => a.id.localeCompare(b.id));
      L.push("", `**${g}** (${list.length})`, "");
      for (const s of list) {
        const name = String(s.frontmatter.name ?? s.id);
        L.push(`- \`${name}\` - ${oneLine(String(s.frontmatter.description ?? ""))}`);
      }
    }
  }

  const others: string[] = [];
  if (ctx.instructions.length) others.push(`**Instructions** (${ctx.instructions.length}): ${ctx.instructions.map((i) => i.id).sort().join(", ")}`);
  if (ctx.subagents.length) others.push(`**Subagents** (${ctx.subagents.length}): ${ctx.subagents.map((a) => String(a.frontmatter.name ?? a.id)).sort().join(", ")}`);
  if (ctx.commands.length) others.push(`**Commands** (${ctx.commands.length}): ${ctx.commands.map((c) => "/" + String(c.frontmatter.name ?? c.id)).sort().join(", ")}`);
  if (ctx.hooks.length || ctx.mcp.length) others.push(`**Hooks** (${ctx.hooks.length}) and **MCP servers** (${ctx.mcp.length})`);
  if (others.length) {
    L.push("", "### Also in the library", "");
    for (const o of others) L.push(`- ${o}`);
  }

  return L.join("\n").trimEnd();
}

/** Replace the content between the overview markers in an existing README; markers must be present. */
export function spliceReadme(existing: string, block: string): string {
  const b = findSoleMarker(existing, README_BEGIN);
  const e = findSoleMarker(existing, README_END);
  if (b === -1 || e === -1 || e < b) throw new Error("README.md is missing the CONTENT OVERVIEW markers");
  return `${existing.slice(0, b + README_BEGIN.length)}\n\n${block}\n\n${existing.slice(e)}`;
}
