name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        platform: [windows-latest, ubuntu-latest, macos-latest]
      fail-fast: false

    runs-on: ${{ matrix.platform }}
    name: Build (${{ matrix.platform }})

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Windows-specific setup
      - name: Install Windows Build Tools
        if: matrix.platform == 'windows-latest'
        uses: microsoft/setup-msbuild@v1.1

      # Ubuntu-specific setup
      - name: Install Linux Dependencies
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get remove -y libappindicator3-1 libappindicator3-dev
          sudo apt-get install -y \
            libgtk-3-dev \
            libwebkit2gtk-4.1-dev \
            librsvg2-dev \
            patchelf \
            libglib2.0-dev \
            build-essential \
            curl \
            wget \
            file \
            libssl-dev \
            libayatana-appindicator3-dev

      # Setup Node and Yarn
      - name: Setup Node and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      # Install Rust with required targets
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'windows-latest' && 'x86_64-pc-windows-msvc' || matrix.platform == 'macos-latest' && 'x86_64-apple-darwin' || 'x86_64-unknown-linux-gnu' }}

      # Debug: List current directory
      - name: List Current Directory
        shell: bash
        run: |
          pwd
          ls -la

      # Setup Yarn properly
      - name: Setup Yarn
        run: |
          corepack enable
          corepack prepare yarn@stable --activate
          yarn --version

      # Install dependencies with verbose logging
      - name: Install Dependencies
        run: |
          yarn install --verbose
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false

      # Debug: Check package.json
      - name: Check package.json
        shell: bash
        run: |
          echo "Package.json content:"
          cat package.json

      - name: Build Turbo Repo
        run: yarn build
        continue-on-error: true

      - name: Install Tauri CLI
        run: yarn global add @tauri-apps/cli

      # Debug: Check src-tauri directory
      - name: Check Tauri Directory
        shell: bash
        run: |
          echo "Checking src-tauri directory:"
          ls -la src-tauri || echo "src-tauri directory not found"

      - name: Build Tauri App
        run: |
          echo "Starting Tauri build..."
          yarn tauri build --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUST_BACKTRACE: 1

      - name: List Build Directory (Debug)
        shell: bash
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la
          echo "Searching for build artifacts:"
          find . -name "*.msi" -o -name "*.deb" -o -name "*.dmg" -o -name "*.app"

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-artifacts
          path: |
            **/target/release/bundle/**/*.msi
            **/target/release/bundle/**/*.deb
            **/target/release/bundle/**/*.dmg
            **/target/release/bundle/macos/*.app/**/*
            **/target/release/bundle/dmg/**/*
          if-no-files-found: warn

  release:
    needs: build
    runs-on: ubuntu-latest
    if: success() || failure()

    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: Display structure of downloaded files
        run: ls -R artifacts/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          fail_on_unmatched_files: false
          files: |
            artifacts/**/*.msi
            artifacts/**/*.deb
            artifacts/**/*.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}